language: python
python:
- '2.7'
install:
- pip install --upgrade pip setuptools wheel
- pip install tqdm
- pip install requests
- python setup.py bdist_wheel
- pip install dist/netpay_ecommerce_python-1.0.4-py2-none-any.whl
script:
- pytest
deploy:
  provider: pypi
  user: developer-netpay
  password:
    secure: T4Pf0z4upbuZ+c2O3Qn/9gQUMdsuORGgPaOqIHXlgxF5fVlsoEZh5na+fg3TOoKhpqfsJyDwbFrfUD66U5YihD1Jt2W3P1uhVeAaCwip7F3iQpYJ88ApQvEuXWUrQRFhZkSOl6alvocptRAG/Ci7CdRlFuH2gY4gedN4lGaPu5griXMxHa6bJBbRh2L8rY+8OiM0o6k9m/lKOy0lpFYcG05SffuKevsoq4Qt0dGZKNbXEY98R3bd0SD3v0aFsktv2U3iMfPZCYM8Bal1xIGEfB0pog8SWHd/f254PWdnoPNidnwPsapG4P7c6q79+8KxBoIuSDgy1AGsHyd1Or+oRiwoY5ya5ojamlBw4p+0Q3CHWajvtxQXBXe4yIGsxBNsDnPgkYLMdAWi4abtGLwsT1WZK+Z4ODXBR09IMTUzm99cQJUvyORfS1mCiZ7Ijr8u/B6eG8G7iWSaaXSArLIxGce6siuyphyeNJDhiBVsglO84ObAE6Clm70fMZ2SLBY6X2Cmfdh0SWwyQSCvn/zrTW9nhAb8qGY5X0MmF6Nas9B/TOn1nU7hND0elwwToaVRMvSQvU1wYFfdOWIrvIwcnxPEVlrXo8gxev7BHF9/b+762Mz1Vw3LBFED2PA6yA4bWd0Fhfc34+reP46pWAJm7x9XZWQNZ9ar9bLXwGZ60/8=
  on:
    branch: master
