language: python
python:
- '2.7'
install:
- pip install --upgrade pip setuptools wheel
- pip install tqdm
- pip install requests
- python setup.py bdist_wheel
- pip install dist/netpay_ecommerce_python-1.0.0-py2-none-any.whl
script:
- pytest
deploy:
  provider: pypi
  user: developer-netpay
  password:
    secure: WUBMDCxxkiKG8XlAwVupCDaj7wzGQehJVjUicCf7rtR5JG12iS6RRLEDetiujadaOTR7jBl6yTIgU5U26mlSKR9Gimk53oFUGXO/iNCxF1C4Lvw9lj6A0qS+jAOTJbE6szn/eSJC4Fk9phdvS/wKM1UOnZz8cL6cV/Q5VnZgBcZS1Yn6F/aSG9lJt3j+mmL6NJddTkAqAKTPQD0EpJu4MkcP6Kr3R7BSFN8OgcdCXlW+KM3ObQs1R7g+Wce0y1C1I/NOouWe3oZWfOHXvaxNiskwEgA7lmu6tp9m5RNYWlzYS4VGXXu+lISMfTut3jqbr6QNVULTJ+rxdzV4plKRgrLb7ycr3ZXU9o8f7NdxfQdjweF38oQ9fqWicdEVCcsBuKnltlMt4SEBM00s9seKZ6KK62bYJwmKO+3vdcvpaCAPx1Ic+VMAG4QMsQSOZlV5vN7aQQVh5b4SOO36myIw766z76hywXDU9dE/mKxNt/tb/9R2YXuZXhcGSFLq7Ofaw8T10DyZjS4Jkd/YB4kzntTAnfZtpC8ATCfnS8VE9EXacF6olXdb5kSnwatxws3oAcl5DfR9E/eiW3SJB0vVY5dhYeQ9ecfI2XsACzCG1NNkeGeSJjXUqLcgLWdVvN//Tz1MqwD2bZA2pZLMhavnhaHc+4IJdDkPeiWQ28wE5PY=
  on:
    branch: master
